%% 
clear
clc
hf = figure('Position',[460 200 1000 600],...
            'Name','detection de paneaux',...
            'NumberTitle','off');
ha = axes('Position',[0.05 0.3 0.51 0.5],...
          'Box','on',...
          'ALimMode','auto');
hb = axes('Position',[0.75 0.5 0.11 0.18],...
          'Box','on',...
          'ALimMode','auto');
hx = uicontrol(hf,...
               'Style','edit',...
               'Position',[750 200 50 30]);
hy = uicontrol(hf,...
               'Style','edit',...
               'Position',[810 200 50 30]);
hread = uicontrol(hf,...
                  'Style','pushbutton',...
                  'Position',[228 90 120 40],...
                  'FontSize',11,...
                  'String','saisir une image',...
                  'CallBack',...
                  ['subplot(ha);'...
                   '[f,p] = uigetfile(''*.ppm;*.jpg;*.bmp'',''please set an input image'');'...
                   'I = imread(f);'...
                   'imshow(I,[]);',...
                   'hold on']);
hdetect = uicontrol(hf,...
                  'Style','pushbutton',...
                  'Position',[600 320 100 40],...
                  'FontSize',11,...
                  'String','detecter',...
                  'CallBack',...
                  ['subplot(hb);',...
                   'I1 = detection(I);',...
                   'I_bw = morph(I1);',...
                   '[circleElement,I1] = detectionCircle(I_bw,I);',...
                   '[content,centerx,centery] = detectionPanel(I1,circleElement);',...
                   'subplot(ha);',...
                   'plot(centerx,centery,''b*'');',...
                   'hold off;',...
                   'set(hx,''String'',centerx);',...
                   'set(hy,''String'',centery);',...
                   'if (content == 1) ',...
                   'set(hz,''String'',''limite vitsse 30'');',...
                   'elseif (content == 2) ',...
                   'set(hz,''String'',''limite vitesse 50'');',...
                   'else ',...
                   'set(hz,''String'',''alert'');',...
                   'end']);
hz = uicontrol(hf,...
               'Style','edit',...
               'Position',[748 150 120 30]);
hxt = uicontrol('Style','text',...
               'Position',[748 235 55 12],...
               'String','X');
hyt = uicontrol('Style','text',...
               'Position',[808 235 55 12],...
               'String','Y');
hname = uicontrol(hf,...
               'Style','text',...
               'Position',[860 500 80 30],...
               'String','YU Xuanlong ZHAO Zixiao',...
               'max',2);